<?php $this->partial('shared/header'); ?>

<form method="post" class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <div class="pull-right">
                    <a class="btn btn-default" href="<?= $ref ?>" type="button">Cancel</a>
                    <button class="btn btn-primary">Save</button>
                </div>
                <h3><?= $title ?></h3>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-3">
            <?= $this->form->field('name') ?>
            <?= $this->form->field('images') ?>
        </div>
        <div class="col-md-9">
            <div class="form-group">
                <label>Images</label>
            </div>
            <div class="row" id="media-list"></div>
            <button class="btn btn-default btn-block" type="button" id="btn-uploader">Add Image</button>
            <div>&#160;</div>
        </div>
    </div>
</form>

<?php $this->partial('shared/footer'); ?>